### ISSUE TITLE
Add character class and level to character selection dropdown

### ISSUE THREAD

**Issue by ryksa92** [EtienneLamoureux/TQVaultAE#125]
Hello.

Could you add more character related information to the list, when I choose my character inventory? I mean, it only shows my character names, but would be nice to see the character level and class name.

Thanks for your work. :)

**Comment by EtienneLamoureux** [comment]
We can consider this, it doesn't seem to unreasonable.

**Comment by ryksa92** [comment]
Thank you. :)

**Comment by hguy** [comment]
With the build "Character Edit" this is done !

**Comment by EtienneLamoureux** [comment]
Right. I'll document and close

**Comment by EtienneLamoureux** [comment]
Dropdown should read as follow, to remain consistent with the multiplayer display of character names: `<char> <class> - Level: <level>`.

The current challenge implementing this solution is that since we don't necessarily load all characters when first opening the vault, the current dropdown is simply populated by reading the character's folder name on the disk, and not by the game data. See `TQData#GetCharacterList`

**Comment by hguy** [comment]
> 
> 
> Dropdown should read as follow, to remain consistent with the multiplayer display of character names: `<char>, <class> - Level: <level>`.
> 
> The current challenge implementing this solution is that since we don't necessarily load all characters when first opening the vault, the current dropdown is simply populated by reading the character's folder name on the disk, and not by the game data. See `TQData#GetCharacterList`

That mean we have to accept to read all characters data to achieve this.

**Comment by EtienneLamoureux** [comment]
Or only do that when we have the character data loaded. Either refresh the dropdown on character load or implement a different dropdown population logic when pre-loading all characters.
