### ISSUE TITLE
Fature request: copy multiple

### ISSUE THREAD

**Issue by teodias** [EtienneLamoureux/TQVaultAE#142]
Hi dear developers,

it would be great if we could copy one or the selected items multiple times.

Yours,
Teodias

**Comment by NorthFury** [comment]
This is already possible. Please make sure it is enabled in the options.

**Comment by teodias** [comment]
I checked options, but couldn't find anything apropriate?
Please explain how to ernable.

**Comment by EtienneLamoureux** [comment]
Allow item copying option. You'll need to copy the item one at a time, but there's no limit to how many times you can copy an item.

As for making multiple copies in a single action, that's trickier because copy puts the new item on your cursor. This is to avoid complicated logic around space management.

**Comment by teodias** [comment]
Is there a difference in logic then copying an item from on panel to the other?
You have to consider remaining space in this also?
Just copy the item x times from the cursor to the active panel?

**Comment by EtienneLamoureux** [comment]
Copying right now only places a copy of the item onto the cursor. What's your full use-case? What are you trying to do?

**Comment by EtienneLamoureux** [comment]
As https://github.com/EtienneLamoureux/TQVaultAE/issues/142#issuecomment-501839444 described: you can copy items. You can make multiple copy by clicking multiple times. Stacks are also copied as-is, a full stack at a time.
