### ISSUE TITLE
Warning about Equipment Block on my character

### ISSUE THREAD

**Issue by graceoflives** [EtienneLamoureux/TQVaultAE#158]
Hi. When I try to open TQVault it shows this message
![image](https://user-images.githubusercontent.com/20889772/59889551-19c42180-93f7-11e9-9c28-49e35e69f440.png)

The vault then shows no equipment for my character.

The shield I'm wearing is Chieftain's Pelta from the original TQ. I don't think it has any problem because when I open other characters, the same warning appears.

**Comment by Frank2201** [comment]
Can confirm. Seems to happen only when pre-loading is turned off.
Never experienced it when the characters were properly loaded from the start.

**Comment by EtienneLamoureux** [comment]
Did you open these characters in-game after the Atlantis patch?

**Comment by Deko360** [comment]
Hello I  have the same bug like the author. The vault then shows no equipment for my character. I 
 did special vault for relics and when I try to open I got this report. Other  vault works properly. 
![błedy tq](https://user-images.githubusercontent.com/52088211/59954259-2773b880-9484-11e9-8f77-ee5ae32823ef.JPG)

**Comment by Frank2201** [comment]
> 
> 
> Did you open these characters in-game after the Atlantis patch?

All characters made after Atlantis.
Opening TQVault with preloading - no error whatsoever
Opening TQVault without preloading, and then opening a character: said error message, all equipment slots empty. The new hero data display also empty.
Not changing anything and closing the TQVault - the character is perfectly fine when opened in the game
Changing the character, like adding 23 items to the various bags and then closing TQVault: the charcter still is perfectly fine ingame -however, the added items do not appear.

**Comment by EtienneLamoureux** [comment]
Thanks for the detailed report!

**Comment by s0da72** [comment]
I'm seeing this issue as well since the last patch..

![image](https://user-images.githubusercontent.com/1280822/59957131-09459280-945b-11e9-83a8-e82d0d52c022.png)

Looking at the debugger, the tex magic number is showing up as 0x02545341 instead of 0x01584554 not sure why.   Even if you use 0x02545341 as the value to compare it just blows up further down.

**Comment by s0da72** [comment]
I just pulled the latest changes for the repo, and it seems to work.   Looks like someone fixed it already.

![image](https://user-images.githubusercontent.com/1280822/59957442-0ac48a00-945e-11e9-8d57-678a2608ef2e.png)

**Comment by EtienneLamoureux** [comment]
TEX magic issue was fixed by #157

**Comment by graceoflives** [comment]
the 3.1.0-alpha seems to have fixed this issue

**Comment by Frank2201** [comment]
Hmmm... wrong. Those are related, yet different issues. 
TEX magic is one, which seems to be solved.
Equipment block empty is another.

Since the TEX magic issue prevented TQVault from loading you got the option to turn off pre-loading. And without preloading the equipment block issue turned up. Now with commit #157 everyone can savely enable preloading again and the equipment bock issue doesn't appear anymore.

However it's still there - the moment you turn off pre-loading the vaults and charaters, everything I wrote earlier is still reproduceable. 
Meaning TEX magic solves, equipment block not solved.

**Comment by EtienneLamoureux** [comment]
Can you open a separate issue with a link to this one so we can track it properly?
