### ISSUE TITLE
Epona's Hog Mane incorrect description

### ISSUE THREAD

**Issue by graceoflives** [EtienneLamoureux/TQVaultAE#199]
The last line in "Bonus to All Pets" apply to whole item, not pets:
In TQVault:
![image](https://user-images.githubusercontent.com/20889772/61168538-eb5edf80-a579-11e9-8e0e-5b7f72dcb38b.png)
In-game:
![image](https://user-images.githubusercontent.com/20889772/61168536-db470000-a579-11e9-8475-17af6265ef34.png)

**Comment by graceoflives** [comment]
looks like a lot of item bonuses does not appear in correct order; some should be above the "Bonus to All Pets" are displayed under; some should be above "Grant Skill" are also displayed under

**Comment by EtienneLamoureux** [comment]
That's simply due to the fact that the game and the tool display the bonuses in different order. All items have a bonus to all stats, but most of these bonuses are actually 0. We display the ones that are not 0, but apparently not always in the same order as the game does (with pet bonuses always at the bottom).

**Comment by hguy** [comment]
@graceoflives can you share the item using a vault file ?

**Comment by afjback** [comment]
I'm gonna help
[eponashogsmane.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/3489337/eponashogsmane.zip)

**Comment by hguy** [comment]
> 
> 
> I'm gonna help
> [eponashogsmane.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/3489337/eponashogsmane.zip)

@afjback : Thank for your help we can look at it now.
