### ISSUE TITLE
Add a configuration option to choose between the two possible tooltip detail levels

### ISSUE THREAD

**Issue by afjback** [EtienneLamoureux/TQVaultAE#225]
Prior to version 3.2 all stats (prefix, base, suffix) displayed combined:
![tqv-aff-combined](https://user-images.githubusercontent.com/53652815/62992073-c2708980-be5a-11e9-851a-cb372b801da9.png)
Since version 3.2 vault have new stats display system, where prefix, base, and suffix stats displayed separately:
![tqv-aff-divided](https://user-images.githubusercontent.com/53652815/62992086-cc928800-be5a-11e9-80f3-d3f90df05206.png)

Surprisingly type of display system may changes during runtime, based on how user is switched to Vault window from another app:
[https://youtu.be/VSkSvN46sXU](https://youtu.be/VSkSvN46sXU)

**Comment by hguy** [comment]
Hi ! 
Thanks for reporting.
It's because the alternative view is toggled by the "LeftAlt" Key.
So every time you hit that key (Task Switching Alt-Tab) it toggle the view.
Nevertheless, its strange that it's happening even when the Vault window has no focus.
We probably should use a more conventional shortcut like <kbd>Ctrl</kbd> + <kbd>t</kbd> or something like that.

**Comment by afjback** [comment]
for most apps single LeftAlt means "Show menu panel", so I consider it bad idea for UX to bind other action to it.

**Comment by graceoflives** [comment]
I'd like it as an option in Configure screen rather than toggle it
