### ISSUE TITLE
Fix crash when loading certain modded characters

### ISSUE THREAD

**Issue by wng-wingie** [EtienneLamoureux/TQVaultAE#280]
Granted that this issue occurs when using a mastery mod, it makes the vault crash when a character is loaded with a certain skill unlocked. The skill consists of a toggled self-buff with the following propreties :

Chance for one of the following :
Burn damage over 3.0 seconds
Frostburn damage over 3.0 seconds
Electrical burn damage over 3.0 seconds

When this skill is unlocked, trying to open the character in the Vault will result in the following error.
![unknown](https://user-images.githubusercontent.com/60035441/72663887-8c18d680-39c5-11ea-8bce-ebbc25571b9b.png)

This report is mainly for determine which party is causing the issue, whether it is TQVault or this particular skill. This weird behavior hasn't been observed anywhere else.

**Comment by EtienneLamoureux** [comment]
Hi, thanks for reporting. 

Can you share your character file?

**Comment by wng-wingie** [comment]
Sure. Apparently the first sufferer of this bug was deleted, but all we needed to do was to create a new character with only this skill unlocked.

The character : [_Temporal.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/4090583/_Temporal.zip)
The mod (if it has any relevance) : https://steamcommunity.com/sharedfiles/filedetails/?id=1949340853

**Comment by ejfudd** [comment]
The root cause of this issue is the naming of the skill database record.  The skill is named `temporalenergy.dbr` which conflicts with the way the player info panel decodes the character stats.
Specifically, it fails when looking for the base strength value in the character file since it looks for the keyword "temp" and it actually finds the skill temporal energy resulting in an unexpected value.
