### ISSUE TITLE
How do I install TQVaultAE? (Vault doesn't work at all)

### ISSUE THREAD

**Issue by chromejoker** [EtienneLamoureux/TQVaultAE#281]
Ive tried ALL the ways you guys say to on the website to get TQvault working...
And that actually caused more problems and new errors ive never seen before..
I re installed the game, i re installed NORMAL TQ and TQIT! nothing works..

now all i want is to be able to use TQVault like i did way back in the day..
Ive spent around 4 hours today trying to get it to work..
i downloaded it 39 different times.. so.. 
help

**Comment by chromejoker** [comment]
Error Loading Resource after every tip, hint or whatever...
bad game path bad language... i dont know what to do...
ive seen people using TQVault and it actually pisses me off so much i cant get it to load...
no matter what i do or try..

My friend, has it working.. he tried to get it to work.. didnt work..
I got his file and everything on a usb, tried that..
Same fucking error.. bad language.. bad game path.

help.

**Comment by chromejoker** [comment]
Oh and the help install bull crap on here doesnt work

**Comment by hguy** [comment]
Looks like your TQVaultAE.exe.config path values are messed up.
1. Unzip TQVault archive into a new directory
2. Run TQVaultAE.exe from that directory
3. If errors on game path discovery, follow the instructions in FAQ `Q. Error Loading Resources. This may be caused by a bad language or game path setting.`
Be careful when setting TQITPath & TQPath if you tried install TQ multiple time on multiple locations.

**Comment by EtienneLamoureux** [comment]
Sorry you're having a hard time installing the tool. The steps provided by @hguy should be able to help, but more info wouldn't hurt:
- Do you have the game standalone? Through a platform? If yes, which one?
- Is your game patched to the latest version available?

Let us know how it goes!
