### ISSUE TITLE
Enable reloading the tool's stashes while the game is running

### ISSUE THREAD

**Issue by hguy** [EtienneLamoureux/TQVaultAE#282]
Refresh TQVaultAE data when files are modified "in game".

- [x] Add a checkbox in settings for activation (Default : false, maybe one for each storage type)
- [ ] ~~Add notification when it happens~~

**Comment by EtienneLamoureux** [comment]
We have to be extremely careful about the conflicts when doing this. People might think it's OK to have both applications opened when in fact, reloading the TQVaultAE's files and modifying them might overwrite files used by the game, resulting in loss of items and/or progress.

**Comment by EtienneLamoureux** [comment]
I'd be curious to see if a proof of concept of this in action. It is my current understanding that the game constantly read/saves to the save file, making it risky at best to play with it in an external process at the same time.

**Comment by hguy** [comment]
> 
> 
> I'd be curious to see if a proof of concept of this in action. It is my current understanding that the game constantly read/saves to the save file, making it risky at best to play with it in an external process at the same time.

@EtienneLamoureux I think the game read/write the files from time to time but it's very quick and it does not lock the files in the meantime.

**Comment by EtienneLamoureux** [comment]
@hguy From what I've seen, that's true. The problem I foresee if that the tool would need to always keep its loaded files up-to-date. Otherwise, you might have:
1. Open the game, start playing
2. <kbd>ALT</kbd>+<kbd>TAB</kbd>, open the tool, move items around
3. Continue playing
4. <kbd>ALT</kbd>+<kbd>TAB</kbd>, open the tool, move items around, *close the tool*
5. Progress done in step 3 is lost, as the tool didn't reload

So this needs to be very thoroughly tested if it's going to be documented as safe to run both programs at the same time.

**Comment by hguy** [comment]
> * [ ]  ~Add notification when it happens~

I think it's a false good idea. Having notification popup every time you, open/close the inventory, load a character, open/close the caravan, rapidly become a hassle.
