### ISSUE TITLE
System.IO.FileLoadException: Could not load text DB

### ISSUE THREAD

**Issue by KatakuriGR** [EtienneLamoureux/TQVaultAE#287]
When i open the TQVaultAE.exe i have this error.
![System IO FileLoadException](https://user-images.githubusercontent.com/62600357/77425638-b62eb080-6ddb-11ea-96d9-f754a70421c5.jpg)

**Comment by EtienneLamoureux** [comment]
It seems you might be running version 3.0.0.0 of the tool Can you try with [the latest version](https://github.com/EtienneLamoureux/TQVaultAE/releases/tag/3.4.0)?

**Comment by EtienneLamoureux** [comment]
Did running the latest version fixed your issue?

**Comment by KatakuriGR** [comment]
> Did running the latest version fixed your issue?

yes thank you!!

**Comment by noplanman** [comment]
Same error pops up for me on latest version (3.5.1)

@EtienneLamoureux How can I help to debug this?

**Comment by noplanman** [comment]
Using 3.4.0 i get the following error:

![tqvaultae-3 4 0-startup-error](https://user-images.githubusercontent.com/9423417/79916120-b3919c00-8417-11ea-8f15-30feee881bf2.png)

**Comment by Bedengus** [comment]
It was working fine, but I changed the path of the executable folder and it gave me that same error.
I tried re-extracting from the exe, but to no avail.
I then reconstructed the old path where it work, but I get the same error too.
I have also 'changed' the TQ path (I had two instalations and deleted the one I did not use) if that has any relevance (the save path of both was the default at documents/my games).
I am using the latest version (3.6).

![image](https://user-images.githubusercontent.com/66883864/84577429-e4c69100-adf6-11ea-9915-f07256d2ccd5.png)

**Comment by EtienneLamoureux** [comment]
Alright, so what do you think the reproduction steps might be?
What was the path where it worked; what was the new one that started the problem?

**Comment by Bedengus** [comment]
> Alright, so what do you think the reproduction steps might be?
> What was the path where it worked; what was the new one that started the problem?

The working path was the random folder I first extracted it to after downloading. I then changed paths to organize it since it was there at random.
But putting it back where it was did not solve it so I am unsure if the path caused that (and the fileload error hints at pathing too); I mentioned them because I have no idea what else could have caused it.
I made a new copy of the game to that other path I had it before the error, but the error is still there.
Before the error there is also a message about the vault path.
Open exe > vault message > crash error.
![image](https://user-images.githubusercontent.com/66883864/84587106-5afae000-ae57-11ea-8c90-ce679c4d04c8.png)

**Comment by noplanman** [comment]
@EtienneLamoureux Does TQAE need to be fully installed on the same machine as TQVaultAE?

I'm running TQAE in a wine port on my Mac and have a VM set up for TQVaultAE (as the port can't install latest .NET versions). I set the paths to point to a share of the wine port folder but that didn't seem to work, or I'm not sure as I get the same error.

Would be cool if this app only needed the actual save game files to manipulate them.
What components of the full game install are required? Maybe I can just copy those over and try again?

**Comment by EtienneLamoureux** [comment]
@Bedengus make sure all the paths listed in `TQVaultAE.exe.config` are correct

**Comment by EtienneLamoureux** [comment]
@noplanman the main the tool needs from the game installation directory is `Titan Quest Anniversary Edition\Database\database.arz`

**Comment by Bedengus** [comment]
There were no paths on the config file; and the 'find game path' is on auto.
I have filled the path to the three places which ask for it, without turning off the auto path, and it went back to working.
It seems it had 'locked' on my old instalation location so it could not find the one I actually used; and so it had no access to those files it needs from the instalation.
Thanks for the help!
And your mod is awesome.

On another hand ever since I installed I have tried changing the mod's language.
I went into the config and put 'en' on the 'UI language' while also disabling 'auto-detect language', but the mod continues on Japanese (my operational system's language). And there is no such option on the mod; only 'game language' which is already in English (and I understand not why it needs the language the game is in; if I change the game's language should I change there too?).
I want to change the vault's UI language so that my non-japophone friend can use it here too.
![image](https://user-images.githubusercontent.com/66883864/84692274-8d542c80-af80-11ea-89b1-3b40210c10cc.png)

**Comment by noplanman** [comment]
@EtienneLamoureux Perfect, I got it running 👍 

I basically copied these over to the VM (seems I didn't need the `Resources`):
- `Titan Quest Anniversary Edition\Database\database.arz`
- `Titan Quest Anniversary Edition\Text`

Then set the paths in the config file.

I still got an error, because I hadn't copied over the actual save games. After doing that, it's now working!

As a suggestion, maybe add error messages instead of letting exceptions pop up messages that aren't helpful for the user 😊

**Comment by HadToRegister** [comment]
This is STILL an issue with version 3.80 the same screensh9ot of File IO Error, using Anniversary Edition.

What are the EXACT Paths that need to be put in to the config files, because the program refuses to run

**Comment by XDeVAlien** [comment]
I confirm that version 3.80 has the same bug.
Titan Quest AE + Ragnarok + Atlantis, game ver. 2.9 STEAM, lang. russian

**Comment by ZombieKabuto** [comment]
I used steam's option to move game directory and since then it's stopped working. Looking at the Log it seems to still be trying to read my old directory. I have added all the necessary paths in the configs and it's still reading the old directory. What gives?
