### ISSUE TITLE
Support for Ragnarök

### ISSUE THREAD

**Issue by TheOne320** [EtienneLamoureux/TQVaultAE#29]
New weapon types and other new items. Can TQVaultAE handle everything?

**Comment by EtienneLamoureux** [comment]
Will investigate, but this is something that will be worked on.

**Comment by EtienneLamoureux** [comment]
The current version of TQVaultAE doesn't support items from the expansion. Proceed with care if you do choose to use it.

**Comment by EtienneLamoureux** [comment]
The first expansion's items are read through a dedicated code path in `Database.cs`. It should be possible to leverage it to read the second xpack's files.

**Comment by KenAlin** [comment]
Hi,

Using the pull request #27 for release 2.5.0.0, I added support for Ragnarök DLC.

Also, because there is now (for AE) only one path for game data, only one database scan is needed : the game will load a bit faster.

**Important note** -> Please backup your files before testing. I haven't finished playing the DLC yet, so maybe there are some additional work to do I'm unaware of.

You can download the release [here](https://github.com/KenAlin/TQVaultAE/releases/tag/2.5.1.0-alpha1).

**Comment by EtienneLamoureux** [comment]
I will update the documentation and bundle a new general release with all the latest fixes this week: I'm sure it will make a lot of people happy.

**Comment by EtienneLamoureux** [comment]
Ragnarök support has been added to the https://github.com/EtienneLamoureux/TQVaultAE/releases/tag/2.5-alpha release.
