### ISSUE TITLE
"The Vault Path was not set." Error

### ISSUE THREAD

**Issue by Brutus1992** [EtienneLamoureux/TQVaultAE#325]
I have problems with installation the TQ Vualt… 

I have windows 10 and a buddy of my windows 7 same problems with the 3.5.1 and the 3.5.0 only on his computer and also not on my windows 10 computer. 

I did try other versions but he remembers the Path… 3.4.0. and 3.3.1 same issues 

can you help ????

![rftgbhn](https://user-images.githubusercontent.com/63917077/79641497-2d1b5700-8198-11ea-866e-37a3cf48678b.png)
![wdefrgtdbfh](https://user-images.githubusercontent.com/63917077/79641498-2db3ed80-8198-11ea-9cba-db58fcb24b2d.png)

**Comment by hguy** [comment]
It mean the path is not set to the Game Install directory or the Game install is incomplete.
Basically it failed to read game files.

**Comment by EtienneLamoureux** [comment]
Specifically this part:

*A. Follow these steps:*
1. *Navigate the the installation folder of TQVaultAE*
2. *Open `TQVaultAE.exe.config` in a text editor (i.e. notepad, **not Microsoft Word**)*
3. *Find the key `AllowCheats` and change the value to `True` or `False`*
    - *`True` will allow you to toggle the cheats individually in the configuration menu*
    - *`False` will disable the cheats completely and make it impossible to enable them in the configuration menu*

**Q. Can TQVaultAE use my old vault files?**

*A. Yes, TQVaultAE is compatible with the legacy TQvault vault files.*

**Q. Error Loading Resources. This may be caused by a bad language or game path setting.**

*A. Follow these steps:*
1. *Navigate the the installation folder of TQVaultAE*
2. *Open `TQVaultAE.exe.config` in a text editor (i.e. notepad, **not Microsoft Word**)*
3. *Replace the following sections:*

```xml
<setting name="AutoDetectGamePath" serializeAs="String">
    <value>True</value>
</setting>
...
<setting name="TQITPath" serializeAs="String">
    <value />
</setting>
<setting name="TQPath" serializeAs="String">
    <value />
</setting>
```

*by (replace the path to the correct one for your computer)*

```xml
<setting name="AutoDetectGamePath" serializeAs="String">
    <value>False</value>
</setting>
...
<setting name="TQITPath" serializeAs="String">
    <value>C:\examplePath\Titan Quest Anniversary Edition</value>
</setting>
<setting name="TQPath" serializeAs="String">
    <value>C:\examplePath\Titan Quest Anniversary Edition</value>
</setting>
```

Let us know if it helped.

**Comment by Brutus1992** [comment]
Thanks for the help... We did install The Vault with your help...

**Comment by vd59** [comment]
<setting name="AutoDetectGamePath" serializeAs="String">
    <value>False</value>
</setting>
...
<setting name="TQITPath" serializeAs="String">
    <value>C:\examplePath\Titan Quest Anniversary Edition</value>
</setting>
<setting name="TQPath" serializeAs="String">
    <value>C:\examplePath\Titan Quest Anniversary Edition</value>
</setting>
НЕ ПОМОГАЕТ!!!!!!!!

**Comment by EtienneLamoureux** [comment]
>  False ... C:\examplePath\Titan Quest Anniversary Edition C:\examplePath\Titan Quest Anniversary Edition НЕ ПОМОГАЕТ!!!!!!!!

You should replace the example paths by the actual paths where the game is installed on your machine.
