### ISSUE TITLE
Has the portuguese translation file been updated?

### ISSUE THREAD

**Issue by Klauhs** [EtienneLamoureux/TQVaultAE#352]
Fantastic!

It would be hard to test the file without building the solution on your local computer. I can bundle it in the next release and if you notice any mistakes, we can always patch later. You can give it to me by zipping it (in a `.zip` file) and drag-drop it in here.

Finally, here is the [Spanish translation file](https://github.com/EtienneLamoureux/TQVaultAE/blob/master/src/TQVaultAE.Presentation/Resources.es.resx) (there might be some missing strings towards the end).

_Originally posted by @EtienneLamoureux in https://github.com/EtienneLamoureux/TQVaultAE/issues/346#issuecomment-651192430_

**Comment by Klauhs** [comment]
...and if you notice any mistakes, we can always patch later.

Ce qui mérite d'être fait mérite d'être bien fait.
[Resources.pt .resx (Latest Version).zip](https://github.com/EtienneLamoureux/TQVaultAE/files/4924377/Resources.pt.resx.(Latest Version.zip)

**Comment by Klauhs** [comment]
...and if you notice any mistakes, we can always patch later.

Ce qui mérite d'être fait mérite d'être bien fait.
[Resources.pt .resx ( Latest Version ).zip](https://github.com/EtienneLamoureux/TQVaultAE/files/4924393/Resources.pt.resx.Latest.Version.zip)

**Comment by Klauhs** [comment]
...and if you notice any mistakes, we can always patch later.

**Ce qui mérite d'être fait mérite d'être bien fait.**

[Resources.pt .resx ( Latest Version ).zip](https://github.com/EtienneLamoureux/TQVaultAE/files/4924404/Resources.pt.resx.Latest.Version.zip)

**Comment by Klauhs** [comment]
...and if you notice any mistakes, we can always patch later.

**### Ce qui mérite d'être fait mérite d'être bien fait.**
[Resources.pt .resx ( Latest Version ).zip](https://github.com/EtienneLamoureux/TQVaultAE/files/4924408/Resources.pt.resx.Latest.Version.zip)

**Comment by Klauhs** [comment]
...and if you notice any mistakes, we can always patch later.

**_Ce qui mérite d'être fait mérite d'être bien fait._**

[Resources.pt .resx ( Latest Version ).zip](https://github.com/EtienneLamoureux/TQVaultAE/files/4924415/Resources.pt.resx.Latest.Version.zip)

**Comment by EtienneLamoureux** [comment]
Hi,

I'm not sure I understand this ticket: this seems to be copy-pasted snippets of past discussion. Could you clarify?

I bundled your latest resx file in [release 3.7.3](https://github.com/EtienneLamoureux/TQVaultAE/releases/tag/3.7.3). It has the [latest translation files you provided](https://github.com/EtienneLamoureux/TQVaultAE/issues/346#issuecomment-656755208). If you have further fixes, I'll be happy to put them in. Additionally, if you'd like to test the translation file yourself, without relying on me preparing a release every time, feel free to download [Visual Studio Community edition](https://visualstudio.microsoft.com/fr/vs/community/), [Git](https://git-scm.com/downloads) and [clone the project](git@github.com:EtienneLamoureux/TQVaultAE.git) (if you're new to Git, I do have a [tutorial](https://etiennelamoureux.com/blog/how-to-use-github), but it is quite in-depth for an absolute beginner). This way, you would be able to build the solution yourself and test your changes quicker. Otherwise, our current slow iterating model of you having to fix the file and me having to bundle a release will have to do. That's what I meant when I said "and if you notice any mistakes, we can always patch later".

If this is about your other issue, https://github.com/EtienneLamoureux/TQVaultAE/issues/351, please note that every contributor to this project is voluntary and works on their own time, when they feel like it and if they have the time to spare. There is no ETA for any fix.

**Comment by Klauhs** [comment]
1)This seems to be copy-pasted snippets of past discussionsh. Could you clarify?
Yes, it's part of # 346 (I was very anxious)
2)If you're new to Git?
Yes i am and thanks for the tutorial.
3)Sorry for my anxiety.

**Comment by EtienneLamoureux** [comment]
Ok no problem! Release 3.7.3 has your latest translation file in it! You can check it out.

**Comment by Klauhs** [comment]
Visual Studio Community will take some time so here's what I fixed and what I didn't have access to.
![1a](https://user-images.githubusercontent.com/67174762/87844147-e6b9bf00-c890-11ea-8b43-a8710251185f.jpg)
![Modifying the command line_7](https://user-images.githubusercontent.com/67174762/87844158-f3d6ae00-c890-11ea-9b27-6db61ba1c54b.jpg)
![Modifying the command line_8](https://user-images.githubusercontent.com/67174762/87844159-f6d19e80-c890-11ea-9a53-3d9ff4109e79.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/67174762/87844160-f9cc8f00-c890-11ea-9c6d-c99a46ed6951.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/67174762/87844161-fc2ee900-c890-11ea-9186-75998710df94.jpg)
[Resources.pt-3.7.3-.resx.zip](https://github.com/EtienneLamoureux/TQVaultAE/files/4941035/Resources.pt-3.7.3-.resx.zip)

**Comment by EtienneLamoureux** [comment]
Thanks for the updated file, it'll be part of the next release!
As for the missing labels, I've added them to this work item: #350
