### ISSUE TITLE
How to donate?

### ISSUE THREAD

**Issue by randomdude163** [EtienneLamoureux/TQVaultAE#365]
I really appreciate this project and would like to buy you a beer ;-) I am a developer myself and know how much effort goes into seemingly simple tools like this.

**Comment by EtienneLamoureux** [comment]
Hi,

Since this is such a long-running and distributed effort, it wouldn't feel right to accept donations for merely managing the repository. If you really want to, you can lookup [our awesome contributors](https://github.com/EtienneLamoureux/TQVaultAE/graphs/contributors) and donate to their other projects :)
