### ISSUE TITLE
System.IO.FileLoadException: Could not load text DB using version 3.80

### ISSUE THREAD

**Issue by HadToRegister** [EtienneLamoureux/TQVaultAE#399]
Just like the screenshot in the other thread titled the same, I get the error in the title and cannot run the Vault to make any settings.

It used to work before.

I keep seeing people say they added "the paths" but they never say the path, or for WHAT ENTRIES in the Config files.

**Comment by ejfudd** [comment]
Vault basically needs to know the following paths with their corresponding settings in the config file:
AutoDetectGamePath - Set this to False.  Defaults to True.
TQPath - Your game install folder.  This folder needs to contain the game database and text database in their respective sub folders.
TQITPath - This is an old setting from when the game had a split installation.  Just set it to the game install folder.
VaultPath - This is where your vault files are stored.

In addition, Vault needs to be able to find your SaveData folder with your character saves.  You should have at least one character created in the Main sub folder as well as the Relic Vault and Transfer Stash files in the Sys folder.  This path is not explicitly set in the config files.

You may also want to disable the LoadAllVaultFiles setting since that can cause issues with modded gear or too many files.

**Comment by EtienneLamoureux** [comment]
https://github.com/EtienneLamoureux/TQVaultAE/issues/287
