### ISSUE TITLE
How to search for completed sets?

### ISSUE THREAD

**Issue by Fa310tx** [EtienneLamoureux/TQVaultAE#418]
I'm not sure if this is the correct place for feature requests, but it would be really nice to be able to list completed sets.
Thanks...
JJ

**Comment by EtienneLamoureux** [comment]
What do you mean exactly?
- List all sets you have completed in all your vaults
- List all sets in the game?

**Comment by Fa310tx** [comment]
I appreciate your response...
I'm talking about completed sets, in the vaults (I guess that might have to include on characters and in character stashes, as well).
For instance, I have a vault for Epic/Legendary items.
Each tab is for a different class of item (swords, shields, chest armor, etc...).
Since set items are together with like items, it's a lot of work to know when a set is finished or what pieces are missing.
I could have set items separated, but then you would have to look in multiple places for a useful item (the class vault, an incomplete sets vault, and a complete sets vault).
It seems like it could be a search option (maybe checkboxes for complete and incomlete sets) or in the set pieces list when you mouse over an item (maybe green for have and red for don't have or check for have and x for don't have).
Currently, I just have a flat text file that I update every so often.
Does that make sense?
Thanks...
JJ

**Comment by hguy** [comment]
HI @Fa310tx 
In the search engine you can easily find all set pieces just by looking by "set name".
![image](https://user-images.githubusercontent.com/31834707/166230332-b5882c49-9da5-40ab-863b-b4a4d27b94d2.png)

Then the result list will tell you,
- if you have all pieces
- where they are

hovering the list item will bring to front the panel containing it.
![image](https://user-images.githubusercontent.com/31834707/166230674-7c5a193e-884b-44b5-a3ba-0d1e7babbc91.png)

Having the "completed set" info inside the tooltip would be nice but will not bring much to the table because the tooltip provide no navigation capabilities to jump from one piece to another.

**_Note : You need to enable "preload all" settings for this to work_**

The current proposal for "Item Hightlighting" (#426) could also help but only in the scope of the visible panels (which may be good enough depending on your item storage strategy).
