### ISSUE TITLE
Hide item forging from users

### ISSUE THREAD

**Issue by Argonil** [EtienneLamoureux/TQVaultAE#450]
The new item editing features, while impressive and useful, are having a negative impact on the community in my experience as a mod author across multiple games and a high-ranking member of the official TQ Discord. When you give common users such powerful tools, they tend to have a hard time resisting the temptation. Many users download TQVault for the storage space and end up with more than they can handle responsibly for their own enjoyment. I suggest adding a few steps between TQVault and the item editing features so that accessing it is more convoluted and out-of-the-way for common users. One idea could be to split the item editing features into an add-on that has to be downloaded separately, and then installed by adding the path in the config file. The section for the path would have to be added manually instead of having a field for it upon installation so that there's no trace of it in the config file by default. These changes would keep the feature available for those who seek it without tempting people into acquiring it.

**Comment by hguy** [comment]
Hi @Argonil 
"Item Editing Features" are disabled by default. It's optional.
![image](https://user-images.githubusercontent.com/31834707/176684810-7a5d2bef-8733-45c4-9fc9-12eb2b848b66.png)

Making this checkbox hard to hit will not make it unreachable for those who want this feature. especially when the tool provide a documentation about it.

> Many users download TQVault for the storage space and end up with more than they can handle responsibly for their own enjoyment. 

Spoiling your fun because you have crafted a too powerful item is a good reason to stop using it by itself. It make no sens to keep playing it ad nauseam.

Why TQVault authors should try to police and control users of a game where 99.9% of them are solo players?
The "Strict Mode" is here to provide a bit of crafting fun without unbalancing the game.

Are you the authoritative person like some kind of police politic on what should be "their" enjoyment and how responsible a TQ player should be?

IMHO multiplayer should inspect who they are grouping with if it's problematic but that's just the 00.1%.

**Comment by Argonil** [comment]
There's a consensus among the veterans in the community that we're seeing it having a negative impact almost daily, it's not just me. Having the editing features stare people in the face is too much of a temptation. Notice how the most popular mods on the Steam Workshop has for a long time been mods that give you extra skill points, attribute points, increased loot and removing enchanting restrictions --- because mods are featured on the front page when they are released and the cheat mods never fell off the front page because they attracted so many users that just happened to visit the workshop and saw the front page. We see it across all games, people are tempted by cheats so much that they can and will cheat the fun out of the game for themselves if the opportunity is presented to them, and item editing is the mother of all cheats. It's fine if it's there for people who seek it out by themselves, but it should not be offered to people who haven't sought it.

**Comment by hguy** [comment]
So what you are saying is that the game mod page is already a cluster of cheat mod and everybody use them already, so we don't need TQVault to do it (weird thinking).
A mod download is one click away either.
So beacause these key features were privilege of mods until then and was the reason why people use them, TQVault should not have it and make it so easy to use?
Basicaly, it step on MOD territory and make some of them obsolete. You're a mod author so i understand your motivation to see this disappear.

> we're seeing it having a negative impact almost daily, it's not just me.

What do you mean? People start crying in chat because their boots are too fast or their sword have a good prefix? Are they quiting the game in rage and suicide because they killed Toxeus too fast?
People that need that feeling of achievement don't use cheats, and those who don't care use mods already (according to what your saying).

Ultimately, @EtienneLamoureux is the one who decide in that matter, but listening to you, everything should be purged (copy items, character edit, items edit). Just for user mental health sake you know.

**Comment by Argonil** [comment]
> So what you are saying is that the game mod page is already a cluster of cheat mod and everybody use them already, so we don't need TQVault to do it (weird thinking). A mod download is one click away either. So because these key features were privilege of mods until then and was the reason why people use them, TQVault should not have it and make it so easy to use? Basicaly, it step on MOD territory and make some of them obsolete. You're a mod author so i understand your motivation to see this disappear.

These features were never the privilege of mods, they go beyond what mods can do and TQVault is used more than mods in general. One of the most frequent questions by new players in the community is "How do I get more stash space?" and then we direct them to TQVault.

> What do you mean? People start crying in chat because their boots are too fast or their sword have a good prefix? Are they quiting the game in rage and suicide because they killed Toxeus too fast? People that need that feeling of achievement don't use cheats, and those who don't care use mods already (according to what your saying).

They trivialize the game for themselves and make it boring for a multitude of reasons. People usually only realize it by the time they've beaten the game and felt like it was a bit of a waste of their time. Additionally, you see trades happen a lot less because people just forge the gear they want now. I'm sure the sense of accomplishment from getting the right gear has been greatly diminished, just like the sense of epicness from overcoming the challenging content in Titan Quest.

**Comment by EtienneLamoureux** [comment]
As discussed, the item forged is a cheat which is disabled by default. A new, more realistic and restricted mode has also been added in the latest release.
