### ISSUE TITLE
New charm that drops from new Dungeon features can't showed properly in TQVaultAE!

### ISSUE THREAD

**Issue by icefreeze88** [EtienneLamoureux/TQVaultAE#453]
Hello guys!
With newest game game patch (v2.10.21192 or Beta Update #5 since Eternal Embers dlc released), TQVaultAE v4.1.0 or v4.0.0 can't showed the charm that drop from new Dungeon properly (doesn't show icon, base stats). 
And if the vaults already stores the charm from that transfer from character to vault from v3.9.0 or lower version one, v4.0.0 or 4.1.0 can't showed anything of it. The only way to see it (no icon, no base stats as i said above) is to transfer the charm back to character by 3.9.0 TQvaultAE then now it can see with V4.1.0 or 4.0.0 in character inventory.

**Comment by hguy** [comment]
Hi @icefreeze88 
It's probably because between game version (Beta, Release) the path to data in game files (bmp, records), must have change. Therefore only the game include code that patch old path to new one from beta to release.
TQVault using new release game files will show broken data for old (beta) path.
It's one of the inconvenient of using TQVault with Beta build.
