### ISSUE TITLE
Fix an issue where points are not refunded when resetting masteries and skills

### ISSUE THREAD

**Issue by GammaO20** [EtienneLamoureux/TQVaultAE#455]
When i reset mastery, the skill points are not return. Its a error?

**Comment by hguy** [comment]
Hi @GammaO20,
I can't replicate the problem. What is the Masteries on your character?

**Comment by Decimous** [comment]
I just tried resetting my masteries (Nature/Earth) and now it says I don't have any skill points either

**Comment by Decimous** [comment]
or at least gave me all the points from leveling my character back, not sure if it gave me the quest reward points back

**Comment by EtienneLamoureux** [comment]
In the meantime, feel free to use TQRespec, which does this exclusively: https://github.com/epinter/tqrespec

**Comment by hguy** [comment]
This problem is related to a form refresh issue.

When you click on the "reset mastery" button the form is closed and the points are refund but when you reopen the form the textbox is not refreshed with the new value, misleading everyone.

Until someone fix it, use the "Save" button or close the tool to force saving and reopen then tool everything is ok then.
