### ISSUE TITLE
"Error System invalid"

### ISSUE THREAD

**Issue by Suchiama** [EtienneLamoureux/TQVaultAE#467]
Hello ! 

I'm here because I can't get Tqvault to work. I just dll the new version (4.3) with the modifications for the "Autodetectgamepath" but I still have a message that blocks me despite the modifications.
I never managed to configure it with Titan Quest AE while with IT it works correctly.

Thanks in advance and have a nice day!

![image](https://user-images.githubusercontent.com/111634501/185738227-95f1f0e7-97b3-4f73-9271-3e079489bbc3.png)

**Comment by hguy** [comment]
You did manualy tweak on the file and broke XML integrity.
Delete the file `UserConfig.xml` and restart the tool.
Most of user settings can be changed safely from the "Setting" window (Button Configure).
![image](https://user-images.githubusercontent.com/31834707/185741767-ebb3ea24-22f1-4bfb-8c90-9c9d34c3432d.png)

**Comment by Suchiama** [comment]
Thank you for the quick reply.

I deleted UserConfig.xml and now I have these error messages (screenshot).

Sorry I'm really new to all this ^^"

![image](https://user-images.githubusercontent.com/111634501/185762242-82d97dae-7a55-45e9-a308-69660f4e7c58.png)

![image](https://user-images.githubusercontent.com/111634501/185762225-a7047b38-9f99-406f-a01d-5381bfeb8c5f.png)

**Comment by hguy** [comment]
The path is still not configured properly.

Here's the procedure.
1. Delete `UserConfig.xml`
2. Start the tool.
A popup appear that let you choose the path of your Titan Quest installation (here's an example).
![image](https://user-images.githubusercontent.com/31834707/185783839-78745e12-b7a2-43f5-8c39-8b3c61b52873.png)
3. That warning popup says that the tool will use the default place for storing your vaults.
![image](https://user-images.githubusercontent.com/31834707/185783919-e4c6d539-f46c-4ea2-9022-a9cd70d46f00.png)
4. That's done.

If you are stuck in this loop with a crash popup about `LoadTextDB()`, it s because you didn't choose the right folder during step 2 or your Titan Quest installation is incomplete.

- If you peeked the wrong folder, go back to step 1.
- If it's your game, open your game launcher (Steam, GOG), use the "check game file integrity" feature and go back to step 1.

**Comment by Suchiama** [comment]
Hi ! 

Don't have popup for choose the path. I just the message error. Or put the path in other file ? 

And after the check, same error. 

Thank you for you time and i don't understand why tqvault not start correctly. 

If you want, ad me on discord, it might be easier.

Suchiama#5063

**Comment by hguy** [comment]
> Don't have popup for choose the path. I just the message error. Or put the path in other file ?

Thats' hard to believe but in that case the FAQ on the Github front page of this tool explain how to manualy edit this path in the `UserConfig.xml` .

**Comment by Suchiama** [comment]
![image](https://user-images.githubusercontent.com/111634501/185786311-c5b8d90f-d80d-4f43-ae4f-f8f414d27184.png)
   
    With that I have the directly the first error screenshot. 

My "userConfig":
        
![image](https://user-images.githubusercontent.com/111634501/185786144-8fa2cfe2-b9f4-4fa0-9004-eca2e579d0b3.png)

It's the same path but error when tqvault start ^^" 
Hard to believe but I always have an error and I don't know where it comes from...

**Comment by hguy** [comment]
You didn't pay attention on reading the FAQ.
![image](https://user-images.githubusercontent.com/31834707/185786738-01be7297-808b-4eeb-8162-eb4b27980ab0.png)

**Comment by Suchiama** [comment]
I'm really bad!!!!!

it works correctly! Thank you so much for your time and patience!!! You are my savior :)

Have a nice day and thank you again for everything!
