### ISSUE TITLE
TQVault Fails to Launch

### ISSUE THREAD

**Issue by FarginIcehole** [EtienneLamoureux/TQVaultAE#91]
I played TQ 5-6 years ago and am getting back into it. I removed my old version of TQVault and downloaded the newest version. When I tried to load it it fails to do anything. Looking at the task manager it shows it launching and then says suspended and it closes. No error message is displayed. I have tried various versions of the Vault and .Net. I have registered the game path in the registry. I have tried the config file as is with auto detect and pointing it to the game. I restored my version from 5 years ago and it still opens (2.2.1.5). I have run in every compatibility mode I could try, disabled my antivirus, run as administrator. I am running windows 10 and have Ragnarok from steam. Is there something obvious I am missing?

**Comment by mschnabel** [comment]
I have the same issue and was interested in the problem. So I downloaded the source code and tried to debug it. If I am right, there seems to be an issue with the VXPLibrary.dll, because once the tool wants to load the ToolTip class, it fails to do so and closes itself.

I tried to comment out all parts where the software is accessing the ToolTip and it worked, the Vault loaded and was usable again, but without any item tooltips - which is also not a real solution to the problem.

Maybe one of the devs can investigate this problem a little further?

**Comment by EtienneLamoureux** [comment]
@msdoseightysix Anything to fix in the code itself? Would you like to submit a pull request?

**Comment by msdoseightysix** [comment]
I haven't fixed anything in the code.

> I just removed every previous installation of TQ Vault on my computer. I also deleted all user specific data in the local AppData folder. I also unregistered the VXPLib.dll via regsvr32.exe. It is now working.

**Comment by EtienneLamoureux** [comment]
Perfect, thanks! I'll close as you found a fix.
